version: "3.7"

services:
  pgadmin:
    image: dpage/pgadmin4

    links:
      - postgres:postgres

    ports:
      - "9001:80"

    environment:
      PGADMIN_DEFAULT_EMAIL: spark@devhausleipzig.de
      PGADMIN_DEFAULT_PASSWORD: spark

  postgres:
    image: postgres:13.0

    environment:
      POSTGRES_DB: spark
      POSTGRES_USER: spark
      POSTGRES_PASSWORD: mysparkpassword

    volumes:
      - ./postgres/data:/var/lib/postgresql/data:rw

    ports:
      - "5432:5432/tcp"
